name: concert-scenarios
on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master, decentralize]
permissions:
  contents: write
jobs:
    scenarios:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: execute_remote_experiment
              run: docker compose -f concert/tests/scenarios/remote_experiment/compose.yml up --abort-on-container-exit
            - name: assert_remote_experiment
              run: |
                cont_id=$(docker container ls -a --filter label=com.docker.compose.project --filter name=remote_experiment --format "{{.ID}}")
                exit_code=$(docker inspect $cont_id --format='{{.State.ExitCode}}')
                chmod +x concert/tests/scenarios/check.sh
                ./concert/tests/scenarios/check.sh $exit_code
            - name: cleanup_remote_experiment
              run: docker compose -f concert/tests/scenarios/remote_experiment/compose.yml down -v
